In [1]:
import numpy as np
q = 0.1 #stepsize
x = np.array([0.012, 1.234, 2.456, 3.789])
print x

[ 0.012  1.234  2.456  3.789]


Mid-Tread quantizer (Encoder):

In [2]:
index = np.round(x/q)
print index

[  0.  12.  25.  38.]


De-quantization (Decoder):

In [3]:
reconstr = index * q
print reconstr

[ 0.   1.2  2.5  3.8]
